# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zaid < Formula
  desc "https://github.com/zaid-language/zaidlang"
  homepage ""
  version "1.0.1"

  depends_on "git"
  depends_on "zsh"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zaid-language/zaidlang/releases/download/v1.0.1/zaidlang_1.0.1_darwin_arm64.tar.gz"
      sha256 "dfab7417cd4e0f6e86f429b2dfeaffa5d3019433de678e8d6e5aabd50af7dead"

      def install
        bin.install "zaid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zaid-language/zaidlang/releases/download/v1.0.1/zaidlang_1.0.1_darwin_amd64.tar.gz"
      sha256 "579b06e9833ea1468e9fda2f2d6272bdb9bb56dacd33110d97127103864511d2"

      def install
        bin.install "zaid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zaid-language/zaidlang/releases/download/v1.0.1/zaidlang_1.0.1_linux_arm64.tar.gz"
      sha256 "21c668845de0b9a034beb2e0f0bcc00aa912ea134c864713db890e60fa953f49"

      def install
        bin.install "zaid"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/zaid-language/zaidlang/releases/download/v1.0.1/zaidlang_1.0.1_linux_armv6.tar.gz"
      sha256 "6ddbdcebb7babc0dd973f5064ea56f4dbcf43f6b28e3d38ca6da9e97d82f4a83"

      def install
        bin.install "zaid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zaid-language/zaidlang/releases/download/v1.0.1/zaidlang_1.0.1_linux_amd64.tar.gz"
      sha256 "cccf853efcb40dec55eded170a20802bd1af35d499159198d4cd697a447aa0f3"

      def install
        bin.install "zaid"
      end
    end
  end
end
